
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TutoringForm.java
 *
 * Created on Dec 18, 2010, 5:22:14 PM
 */

/**
 *
 * @author Jeremy
 */
public class TutoringForm extends javax.swing.JFrame {

    /** Creates new form TutoringForm */
    public TutoringForm() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        paymentTextField = new javax.swing.JTextField();
        addPaymentButton = new javax.swing.JButton();
        quitAppButton = new javax.swing.JButton();
        makeReportButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTextArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tutoring Time in Minutes");

        jLabel2.setText("Payment in Dollars and Cents");

        addPaymentButton.setText("Add");
        addPaymentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPaymentButtonActionPerformed(evt);
            }
        });

        quitAppButton.setText("Quit");
        quitAppButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitAppButtonActionPerformed(evt);
            }
        });

        makeReportButton.setText("Report");
        makeReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                makeReportButtonActionPerformed(evt);
            }
        });

        displayTextArea.setColumns(20);
        displayTextArea.setRows(5);
        jScrollPane1.setViewportView(displayTextArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(timeTextField)
                            .addComponent(paymentTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(makeReportButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addPaymentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(quitAppButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(timeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(addPaymentButton)
                    .addComponent(paymentTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(makeReportButton)
                        .addGap(18, 18, 18)
                        .addComponent(quitAppButton))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitAppButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitAppButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_quitAppButtonActionPerformed

    private void addPaymentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPaymentButtonActionPerformed
        // A couple of floats to for extaraction from the form
        float[] tmpArray = new float[2];

        // Get the value from the timeTextField, and convert to float
        // Throws an exception if it can't.  Catch the exception and display
        // a message about the bad value
        try {
            tmpArray[0] = Float.parseFloat(
                this.timeTextField.getText()
            );
            // If time entered is less than 0 throw exception
            if (tmpArray[0] <= 0){
                throw new InvalidTimeException("time must be greater than zero");
            }
            // If time worked exceeds 4 hours, throw exception
            if (tmpArray[0] > 240){
                throw new InvalidTimeException("cannot exceeds 4 hours per session");
            }
        }
        catch (InvalidTimeException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            this.timeTextField.grabFocus();
            this.timeTextField.selectAll();
            return;
        }
        catch (Exception e){
            JOptionPane.showMessageDialog(this, "Must enter a floating point number in the time field");
            this.timeTextField.grabFocus();
            this.timeTextField.selectAll();
            return;
        }
        // Get the value from the timeTextField, and convert to float
        // Throws an exception if it can't.  Catch the exception and display
        // a message about the bad value
        try {
            tmpArray[1] = Float.parseFloat(
                    this.paymentTextField.getText()
            );
            if (tmpArray[1] <= 0) {
                throw new InvalidEarningsException("You should have been paid");
            }
        }
        catch (InvalidEarningsException e){
            JOptionPane.showMessageDialog(this, e.getMessage());
            this.paymentTextField.grabFocus();
            this.paymentTextField.selectAll();
            return;
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Must Enter a floating point number for the payment made field");
            this.paymentTextField.grabFocus();
            this.paymentTextField.selectAll();
            return;
        }
        
        // Java doesn't have dynamicly sized arrays (stupid), so jump through
        // hoops.  If this.timePaymentArray is initialized, increase its length
        // by 1 and set the new element to tmpArray, otherwise, init it and
        // set element 0 to tmpArray
        try {
            float[][] newArray = new float [this.timePaymentArray.length+1][2];
            System.arraycopy(this.timePaymentArray, 0, newArray, 0, this.timePaymentArray.length);
            newArray[this.timePaymentArray.length] = tmpArray;
            this.timePaymentArray = newArray;
        }
        catch (Exception e){
            this.timePaymentArray = new float[1][2];
            this.timePaymentArray[0] = tmpArray;
        }

        // Build output string
        this.displayTextArea.setText("*************************\nRaw Earnings Data\n\n");
        this.displayTextArea.append("Minutes\tEarnings\n");

        for (int i=0; i<this.timePaymentArray.length; i++){
            this.displayTextArea.append(this.timePaymentArray[i][0] + "\t");
            this.displayTextArea.append(this.timePaymentArray[i][1] + "\n");
        }
        this.displayTextArea.append("*************************");
        // reset timeTextField and paymentTextField to empty string
        this.timeTextField.setText("");
        this.paymentTextField.setText("");
        // place the cursor back in timeTextField
        this.timeTextField.grabFocus();
    }//GEN-LAST:event_addPaymentButtonActionPerformed

    private void makeReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_makeReportButtonActionPerformed
        float timetotal=0, earntotal=0;

        this.displayTextArea.setText("");
        try {
            for (int i=0; i<this.timePaymentArray.length; i++){
                this.displayTextArea.append(
                        String.format("Minutes = %.2f\t", this.timePaymentArray[i][0]));
                this.displayTextArea.append(
                        String.format("Earnings = $%.2f\n", this.timePaymentArray[i][1]));

                timetotal = timetotal + this.timePaymentArray[i][0];
                earntotal = earntotal + this.timePaymentArray[i][1];
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, "Missing Data");
            return;
        }
        this.displayTextArea.append("\n\n***************\n");
        this.displayTextArea.append("Report for your wages to date:\n\n");
        this.displayTextArea.append(
                String.format("Total minutes spent tutoring: %.2f\n", timetotal));
        this.displayTextArea.append(
                String.format("Total Earnings: $%.2f\n", earntotal));
        float avg = earntotal/(timetotal/60);
        this.displayTextArea.append(
                String.format("Average per hour wages: $%.2f\n\n", avg));
        this.displayTextArea.append(
                String.format("Minimum Wage is currently: $%.2f\n\n", this.minwage));
        this.displayTextArea.append("Your wages per hour are ");
        if (avg < this.minwage) {
            this.displayTextArea.append("below average");
        }
        else if (avg >= this.minwage && avg <= (this.minwage*2)){
            this.displayTextArea.append("average");
        }
        else if (avg > (this.minwage*2)){
            this.displayTextArea.append("above average");
        }
        else {
            JOptionPane.showMessageDialog(this, "Something went terribly wrong");
        }
        this.timeTextField.grabFocus();
    }//GEN-LAST:event_makeReportButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TutoringForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPaymentButton;
    private javax.swing.JTextArea displayTextArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton makeReportButton;
    private javax.swing.JTextField paymentTextField;
    private javax.swing.JButton quitAppButton;
    private javax.swing.JTextField timeTextField;
    // End of variables declaration//GEN-END:variables

    // Other var not declared by the gui builder
    private float[][] timePaymentArray;

    final float minwage = 6.55f;
}
